### ISSUE TITLE
Missing gitignore file in /backend

### ISSUE THREAD

**Issue by balayokesh** [SanjaySargam/MyTradeHive#3]
Hi, I just want to suggest adding a `.gitignore` file inside `/backend` folder.  I can see `node_modules` have been uploaded to github, which may not be necessary.

Feel free to close this issue, if it's not necessary.

**Comment by sanjaysargam** [comment]
@balayokesh Yeah sure. Go ahead

**Comment by lakshita10341** [comment]
can i work on this issue

**Comment by sanjaysargam** [comment]
Hi @lakshita10341, already @balayokesh raised the issue so we should give priority to him. If @balayokesh is ok with it, then I have no issues. 
But you still find issues in repo and raise it. I'll assign you. It could be any minor improvements

**Comment by balayokesh** [comment]
> Hi @lakshita10341, already @balayokesh raised the issue so we should give priority to him. If @balayokesh is ok with it, then I have no issues. 
> But you still find issues in repo and raise it. I'll assign you. It could be any minor improvements 

I have no issues. You can assign this to @lakshita10341
