### ISSUE TITLE
 The misalignment in the "Home" text on your website.'Text Alignment Issue on Home Page Navigation'

### ISSUE THREAD

**Issue by Madhuulagishetty** [SanjaySargam/MyTradeHive#5]
"On the Home page of the TradeHive website, the text 'Home' descriptions is not properly aligned ".

**Comment by Madhuulagishetty** [comment]
hey can you assign this issue to me ?

**Comment by Madhuulagishetty** [comment]
@SanjaySargam

**Comment by sanjaysargam** [comment]
@Madhuulagishetty Assigned 
Go ahead
